#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu

basedir="$(dirname "$0")"
mp3_prefix="http://src.xvzf.io/mp3/"
feed_url="http://xvzf.io/podcast.atom"

"$basedir/mkpodcast" "$feed_url" "$mp3_prefix" "/var/www/xvzf.io/shared/mp3/"
