#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu

b="$(dirname "$0")"
p="http://localhost:8901"

"$b/mkpodcast" "$p/feed.atom" "$p" "$b/test/" | tee "$b/test/feed.atom"
cd "$b/test"
echo
echo "http://localhost:8901/feed.atom"
echo
python -m SimpleHTTPServer 8901
